# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(640, 480)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SettingsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(460, 440, 166, 27))
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.Network = QtWidgets.QGroupBox(parent=SettingsDialog)
        self.Network.setGeometry(QtCore.QRect(10, 10, 461, 101))
        self.Network.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.Network.setObjectName("Network")
        self.hostname_label = QtWidgets.QLabel(parent=self.Network)
        self.hostname_label.setGeometry(QtCore.QRect(10, 30, 150, 20))
        self.hostname_label.setMinimumSize(QtCore.QSize(150, 20))
        self.hostname_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.hostname_label.setObjectName("hostname_label")
        self.mimetic_port_label = QtWidgets.QLabel(parent=self.Network)
        self.mimetic_port_label.setGeometry(QtCore.QRect(170, 30, 140, 20))
        self.mimetic_port_label.setMinimumSize(QtCore.QSize(140, 20))
        self.mimetic_port_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.mimetic_port_label.setObjectName("mimetic_port_label")
        self.dancer_port_label = QtWidgets.QLabel(parent=self.Network)
        self.dancer_port_label.setGeometry(QtCore.QRect(310, 30, 140, 20))
        self.dancer_port_label.setMinimumSize(QtCore.QSize(140, 20))
        self.dancer_port_label.setMaximumSize(QtCore.QSize(100, 20))
        self.dancer_port_label.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.dancer_port_label.setObjectName("dancer_port_label")
        self.host = QtWidgets.QLineEdit(parent=self.Network)
        self.host.setGeometry(QtCore.QRect(10, 60, 150, 30))
        self.host.setMinimumSize(QtCore.QSize(150, 30))
        self.host.setMaximumSize(QtCore.QSize(130, 20))
        self.host.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.host.setObjectName("host")
        self.mimetic_port = QtWidgets.QLineEdit(parent=self.Network)
        self.mimetic_port.setGeometry(QtCore.QRect(170, 60, 130, 30))
        self.mimetic_port.setMinimumSize(QtCore.QSize(120, 30))
        self.mimetic_port.setMaximumSize(QtCore.QSize(130, 20))
        self.mimetic_port.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.mimetic_port.setObjectName("mimetic_port")
        self.dancer_port = QtWidgets.QLineEdit(parent=self.Network)
        self.dancer_port.setGeometry(QtCore.QRect(310, 60, 130, 30))
        self.dancer_port.setMinimumSize(QtCore.QSize(120, 30))
        self.dancer_port.setMaximumSize(QtCore.QSize(130, 20))
        self.dancer_port.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.dancer_port.setObjectName("dancer_port")
        self.mirroring = QtWidgets.QGroupBox(parent=SettingsDialog)
        self.mirroring.setGeometry(QtCore.QRect(480, 9, 131, 101))
        self.mirroring.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.mirroring.setObjectName("mirroring")
        self.mirror_video = QtWidgets.QCheckBox(parent=self.mirroring)
        self.mirror_video.setGeometry(QtCore.QRect(10, 30, 115, 30))
        self.mirror_video.setMinimumSize(QtCore.QSize(110, 30))
        self.mirror_video.setMaximumSize(QtCore.QSize(115, 30))
        self.mirror_video.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.mirror_video.setAutoFillBackground(False)
        self.mirror_video.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.mirror_video.setChecked(True)
        self.mirror_video.setObjectName("mirror_video")
        self.flip_blossom = QtWidgets.QCheckBox(parent=self.mirroring)
        self.flip_blossom.setGeometry(QtCore.QRect(10, 60, 115, 30))
        self.flip_blossom.setMinimumSize(QtCore.QSize(110, 30))
        self.flip_blossom.setMaximumSize(QtCore.QSize(115, 30))
        self.flip_blossom.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.flip_blossom.setAutoFillBackground(False)
        self.flip_blossom.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.flip_blossom.setObjectName("flip_blossom")
        self.output_directory_group = QtWidgets.QGroupBox(parent=SettingsDialog)
        self.output_directory_group.setGeometry(QtCore.QRect(10, 120, 601, 80))
        self.output_directory_group.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.output_directory_group.setObjectName("output_directory_group")
        self.output_directory = QtWidgets.QLineEdit(parent=self.output_directory_group)
        self.output_directory.setGeometry(QtCore.QRect(10, 40, 480, 27))
        self.output_directory.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.output_directory.setObjectName("output_directory")
        self.browse_button = QtWidgets.QPushButton(parent=self.output_directory_group)
        self.browse_button.setGeometry(QtCore.QRect(500, 40, 88, 27))
        self.browse_button.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.browse_button.setObjectName("browse_button")
        self.gaze_calibration = QtWidgets.QGroupBox(parent=SettingsDialog)
        self.gaze_calibration.setGeometry(QtCore.QRect(10, 210, 521, 191))
        self.gaze_calibration.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.gaze_calibration.setObjectName("gaze_calibration")
        self.left_looking = QtWidgets.QGroupBox(parent=self.gaze_calibration)
        self.left_looking.setGeometry(QtCore.QRect(10, 30, 170, 141))
        self.left_looking.setMaximumSize(QtCore.QSize(280, 150))
        self.left_looking.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.left_looking.setObjectName("left_looking")
        self.left_threshold = QtWidgets.QLineEdit(parent=self.left_looking)
        self.left_threshold.setGeometry(QtCore.QRect(20, 60, 113, 27))
        self.left_threshold.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.left_threshold.setObjectName("left_threshold")
        self.is_left_looking = QtWidgets.QCheckBox(parent=self.left_looking)
        self.is_left_looking.setEnabled(False)
        self.is_left_looking.setGeometry(QtCore.QRect(20, 30, 130, 25))
        self.is_left_looking.setMinimumSize(QtCore.QSize(130, 25))
        self.is_left_looking.setMaximumSize(QtCore.QSize(130, 25))
        self.is_left_looking.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #444;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: green;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(192, 191, 188);\n"
"}")
        self.is_left_looking.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.is_left_looking.setCheckable(True)
        self.is_left_looking.setChecked(False)
        self.is_left_looking.setObjectName("is_left_looking")
        self.set_current_left = QtWidgets.QPushButton(parent=self.left_looking)
        self.set_current_left.setGeometry(QtCore.QRect(30, 100, 88, 27))
        self.set_current_left.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.set_current_left.setObjectName("set_current_left")
        self.left_looking_2 = QtWidgets.QGroupBox(parent=self.gaze_calibration)
        self.left_looking_2.setGeometry(QtCore.QRect(340, 30, 170, 141))
        self.left_looking_2.setMaximumSize(QtCore.QSize(280, 150))
        self.left_looking_2.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.left_looking_2.setObjectName("left_looking_2")
        self.right_threshold = QtWidgets.QLineEdit(parent=self.left_looking_2)
        self.right_threshold.setGeometry(QtCore.QRect(20, 60, 113, 27))
        self.right_threshold.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.right_threshold.setObjectName("right_threshold")
        self.is_right_looking = QtWidgets.QCheckBox(parent=self.left_looking_2)
        self.is_right_looking.setEnabled(False)
        self.is_right_looking.setGeometry(QtCore.QRect(20, 30, 130, 25))
        self.is_right_looking.setMinimumSize(QtCore.QSize(130, 25))
        self.is_right_looking.setMaximumSize(QtCore.QSize(130, 25))
        self.is_right_looking.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #444;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: green;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(192, 191, 188);\n"
"}")
        self.is_right_looking.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.is_right_looking.setCheckable(True)
        self.is_right_looking.setChecked(False)
        self.is_right_looking.setObjectName("is_right_looking")
        self.set_current_right = QtWidgets.QPushButton(parent=self.left_looking_2)
        self.set_current_right.setGeometry(QtCore.QRect(30, 100, 88, 27))
        self.set_current_right.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.set_current_right.setObjectName("set_current_right")
        self.neutral_looking = QtWidgets.QCheckBox(parent=self.gaze_calibration)
        self.neutral_looking.setEnabled(False)
        self.neutral_looking.setGeometry(QtCore.QRect(190, 50, 140, 25))
        self.neutral_looking.setMinimumSize(QtCore.QSize(1, 25))
        self.neutral_looking.setMaximumSize(QtCore.QSize(140, 25))
        self.neutral_looking.setStyleSheet("QCheckBox::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    border-radius: 3px;\n"
"    border: 1px solid #444;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background-color: green;\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    background-color: rgb(192, 191, 188);\n"
"}")
        self.neutral_looking.setLocale(QtCore.QLocale(QtCore.QLocale.Language.English, QtCore.QLocale.Country.UnitedStates))
        self.neutral_looking.setCheckable(True)
        self.neutral_looking.setChecked(False)
        self.neutral_looking.setObjectName("neutral_looking")

        self.retranslateUi(SettingsDialog)
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Blossom LASIGE Research - Settings"))
        self.Network.setTitle(_translate("SettingsDialog", "Network"))
        self.hostname_label.setText(_translate("SettingsDialog", "Host"))
        self.mimetic_port_label.setText(_translate("SettingsDialog", "Mimetic Port"))
        self.dancer_port_label.setText(_translate("SettingsDialog", "Dancer Port"))
        self.host.setPlaceholderText(_translate("SettingsDialog", "localhost"))
        self.mimetic_port.setPlaceholderText(_translate("SettingsDialog", "8001"))
        self.dancer_port.setPlaceholderText(_translate("SettingsDialog", "8002"))
        self.mirroring.setTitle(_translate("SettingsDialog", "Mirroring"))
        self.mirror_video.setText(_translate("SettingsDialog", "Mirror Video"))
        self.flip_blossom.setText(_translate("SettingsDialog", "Flip Blossoms"))
        self.output_directory_group.setTitle(_translate("SettingsDialog", "Output Directory"))
        self.browse_button.setText(_translate("SettingsDialog", "Browse"))
        self.gaze_calibration.setTitle(_translate("SettingsDialog", "Gaze Calibration"))
        self.left_looking.setTitle(_translate("SettingsDialog", "Left Looking Threshold"))
        self.is_left_looking.setText(_translate("SettingsDialog", "Looking Left?"))
        self.set_current_left.setText(_translate("SettingsDialog", "Set current"))
        self.left_looking_2.setTitle(_translate("SettingsDialog", "Right Looking Threshold"))
        self.is_right_looking.setText(_translate("SettingsDialog", "Looking Right?"))
        self.set_current_right.setText(_translate("SettingsDialog", "Set current"))
        self.neutral_looking.setText(_translate("SettingsDialog", "Neutral Looking"))
